### ISSUE TITLE
Extra garbage is printed to the terminal after v0.2.0

### ISSUE THREAD

**Issue by xTrayambak** [treeform/pretty#13]
Hello, I've noticed that a lot more stuff than needed is being printed out after 0.2.0.

![image](https://github.com/user-attachments/assets/423cca5c-2f99-4db4-b705-37f6998f0e71)

Here's a basic example:
```nim
import pretty

print @["Hello", "Hi"]
```
Instead of just pretty-printing the seq, the characters are printed out sequentially. You seem to have forgotten to remove a debug "echo" statement [here](https://github.com/treeform/pretty/blob/9e770046c5cdf23d395d6b21c4657345481b1c76/src/pretty.nim#L69)

**Comment by AnkyPainter** [comment]
As a quick fix for this, if you go into the 'pretty.nim' file. In the file should see a procedures 'escapeString' comment out or delete the `echo (r: r, i: r.int32)`.

Should fix the problem. Not too sure why, but guess it was left in by mistake?

**Comment by AnkyPainter** [comment]
As a quick fix for this, go to 'pretty.nim' file and search for a procedure called 'escapeString', then just comment out the line
`echo (r: r, i: r.int32)`.

**Comment by incansvl** [comment]
I ran into the same problem with, apparently caused by a debug line left in the code, not fixed after a year.

Any chance someone more competent with Nim than I would be willing to fork this to update it?

**Comment by xTrayambak** [comment]
I just recommend pinning your version of `pretty` to 0.1.0 to fix this for now.
